Edited the Getting Started parts of the documentation for grammar, clarity, and style
MonoGame/MonoGame pull request #7374
Opened 2020-10-10 07:28 UTC by HopefulFrog

One of the main changes I made was removing references to "we" and "let's", so as not to directly reference the author of the documentation, to maintain formality.

I also made other various edits to grammar, sentence structure, and so on.

If these changes are acceptable, I can do the same for the rest of the documentation.

2020-10-10 10:00 UTC, harry-cpp requested changes
Great work @HopefulFrog ! I left a couple of notes, once those are fixed I'll merge this asap.

2020-10-10 10:00 UTC, harry-cpp commented on Documentation/articles/getting_started/2_creating_a_new_project_vs.md
> +Next, type in a name for your project. For this tutorial, **Pong** will be used (note: project names cannot contain spaces). After you've entered the name, click on the **...** button next to the Loc
> choose a directory to contain your project.

That doesn't sound right.

2020-10-10 10:00 UTC, harry-cpp commented on Documentation/articles/getting_started/2_creating_a_new_project_vs.md
> +If everything went correctly, you should see a project named **Pong** (or whatever name you decided on) open up like in the picture below. To run your game, simply press the big **Play Button** in th
> (or whatever name you decided on)

Feels redundant as we specified that we will use Pong as our project name for the tutorial.

2020-10-10 10:00 UTC, harry-cpp commented on Documentation/articles/getting_started/2_creating_a_new_project_vsm.md
> +On the following dialog, type in a name for your project. For this tutorial, **Pong** will be used (note: project names cannot contain spaces). After you've entered the name, click on the **Browse**
Same comment from above.

2020-10-10 10:00 UTC, harry-cpp commented on Documentation/articles/getting_started/2_creating_a_new_project_vsm.md
> +If everything went correctly, you should see a project named **Pong** (or whatever name you decided on) open up like in the picture below. To run your game, simply press the big **Play Button** in th
Same comment from above.

2020-10-10 10:00 UTC, harry-cpp commented on Documentation/articles/getting_started/4_adding_content.md
> +If you haven't already, you'll need to install the MGCB-Editor for managing your content. For details on getting access to this tool, see the [installation instructions here](~/articles/tools/mgcb_ed
MGCB-Editor -> MGCB Editor

2020-10-10 10:00 UTC, harry-cpp commented on Documentation/articles/getting_started/4_adding_content.md
> +> If you do not see the **mgcb-editor-wpf** option when you right-click and select **Open With**, then please review the [Tools documentation](~/articles/tools/tools.md) for installing the MGCB Edito
You don't need to open file explorer, you can use open with, select mgcb-editor-wpf, and than click open. There is a bug in VS that doesn't want to properly set the default editor.

2020-10-10 10:00 UTC, harry-cpp commented on Documentation/articles/getting_started/4_adding_content.md
> +Next, find the LoadContent method. Here, retrieve the "ball" sprite from the Content project and store it in the **ballTexture** private variable using the **Content.Load()** method, with the type of
Very awkward wording.

2020-10-10 17:30 UTC, HopefulFrog commented
@harry-cpp I've made changes in an effort to address the problems you brought up.

2020-10-14 12:00 UTC, harry-cpp commented
Thanks @HopefulFrog , merging!

2020-10-14 12:00 UTC, merged