Update Game.cs
MonoGame/MonoGame pull request #7528
Opened 2021-06-26 04:05 UTC by SAJenkin

Fixed the crashing issue that occurred due to _TargetElapsedTime being larger than _maxElapsedTime.

2021-06-26 18:09 UTC, mrhelmut commented
I would suggest to address this within the ```TargetElapsedTime``` setter here:

https://github.com/MonoGame/MonoGame/blob/8ff767ce939900f03816d37b4d92bb0b1ff8aa57/MonoGame.Framework/Game.cs#L247

This case is handled in the ```MaxElapsedTime``` by throwing an exception if the value is lesser than ```TargetElapsedTime```: 

https://github.com/MonoGame/MonoGame/blob/8ff767ce939900f03816d37b4d92bb0b1ff8aa57/MonoGame.Framework/Game.cs#L220

I would do the same in ```TargetElapsedTime``` by throwing an ```ArgumentOutOfRangeException``` if the ```value``` is greater than ```NaxElapsedTime```.

Github tip: if you write "Fixes #6679" in your post, github will automatically close the issue if this PR gets merged.

2021-06-26 19:52 UTC, SAJenkin commented
I see, I think I may have misread that max elapsed time was being changed and therefore thought TargetElapsedTime should be updated at that same time. thank you for the advice. I've made the necessary changes but I've noticed that TargetElapsedTime isn't allowed to be zero but MaxElapsedTime is, is there a reason for this or should MaxElapsedTime also be larger than zero?

2021-06-27 11:02 UTC, mrhelmut commented
Because it would generate an infinite loop here:

https://github.com/MonoGame/MonoGame/blob/8ff767ce939900f03816d37b4d92bb0b1ff8aa57/MonoGame.Framework/Game.cs#L561

2021-06-27 17:13 UTC, SAJenkin commented
but shouldn't maxElapsedTime be forced to be greater than zero as well?

2021-07-02 08:56 UTC, mrhelmut requested changes

2021-07-02 08:59 UTC, mrhelmut commented
> but shouldn't maxElapsedTime be forced to be greater than zero as well?

Maybe, but maybe there are uses where a zero accumulated time should be possible and desired. I would prefer to leave it be as-is for now.

2021-07-02 12:58 UTC, SAJenkin commented on MonoGame.Framework/Game.cs
> +                        "The time can not be larger than maxElapsedTime", default(Exception));
Done.

2021-07-02 16:37 UTC, mrhelmut commented
Thanks!

2021-07-02 16:37 UTC, merged