Added instructions for targeting M1.
MonoGame/MonoGame pull request #7990
Opened 2023-02-20 16:56 UTC by davidhesselbom

Maybe it's obvious to everyone else, but I kept trying to build for M1 using this command since MonoGame is supposedly able to build M1 native binaries now.

I don't know if anything else needs changing to publish for M1, but the example Info.plist file says

```xml
    <key>LSMinimumSystemVersion</key>
    <string>10.15</string>
```

and I take it that number should be something higher for M1 apps?

2023-02-27 02:12 UTC, stromkos commented
Does it not build and run without these changes?

2023-02-28 16:43 UTC, davidhesselbom commented
Honestly, I haven't been able to run anything I've built on Windows on a Mac yet. Maybe it's because I don't have a certificate to sign the binaries with (I'm a hobbyist, not a professional), or maybe because I put files in the wrong folders inside the application bundle (the instructions aren't clear on where the DLLs and all the other non-content files should go).

Either way, the binary built with the `osx-arm64` flag is shown as an Apple Silicon binary, while a binary built with the `osx-x64` flag will be shown as an Intel binary. This suggests that in order to build a native M1 binary, you do need to use the `osx-arm64` flag. Not that I know whether it makes any difference for performance (or otherwise).

2023-04-18 10:46 UTC, harry-cpp requested changes

2023-04-18 10:46 UTC, harry-cpp commented on Documentation/articles/packaging_games.md
> +From the .NET CLI (x86):
Typo, was supposed to be `x64`.

2023-04-18 17:03 UTC, davidhesselbom commented on Documentation/articles/packaging_games.md
> +From the .NET CLI (x86):
Lol yeah, sorry!

2023-04-19 12:58 UTC, harry-cpp commented
Actually looking at the rest of instructions this isn't enough, you would just end up making an executable for either the x64 or arm64, not both. I'll look into updating the instructions later this week.

2023-04-19 15:26 UTC, mrhelmut commented
Yep, to fully support macOS to modern standard, you have to produce both an x64 and an arm64 executable and fuse them into a universal executable.

This is a step that .NET doesn't support and doesn't intend to support for the foreseeable future, so this will imply a command line call to ```lipo``` to merge them.

2023-04-19 17:51 UTC, harry-cpp commented
New fixed instructions PR is up: https://github.com/MonoGame/MonoGame/pull/8022

2023-04-19 17:51 UTC, closed without merging