Fix MGCB Color parsing error on ColorKeyColor
MonoGame/MonoGame pull request #8167
Opened 2024-02-09 05:20 UTC by JakeLegendXIII

This is a fix for #8154 . There are multiple ways to do this, and I even had a regex version... But I went with kind a simpler more old school way. Please feel free to make any suggestions or request any changes to it!

- Added code that checks for the XNA format {R:0 G:0 B:0 A:0} and parses it into a Color. If the format is the r,g,b,a format it is handled as it was before. 
- Updated the exception message to include both formats.

-Unrelated to this change specifically, but I updated the Help link in the MGCB Editor while I was in there to correctly point to the website after the latest changes.

2024-02-09 09:04 UTC, mrhelmut commented
It looks good to me! Thanks for grabbing it!

@SimonDarksideJ do you happen to know if the format can be a mix like ```{A:0 B:0 G:0 R:0}``` or is it always expected to be RGBA? If it's always RGBA, then this PR seems valid.

2024-02-09 16:57 UTC, SimonDarksideJ approved these changes

2024-02-09 17:09 UTC, SimonDarksideJ requested changes
Can we also have some Unit Tests of possible testing both combinations with various content types?

2024-02-10 02:50 UTC, JakeLegendXIII commented
Hey @SimonDarksideJ makes sense to me. There were no tests on this file today so I ended up creating a new file. There are positive and negative test cases for each. I made sure that Cornflower Blue and MonoGame orange were two of the test colors :)

2024-02-10 09:21 UTC, mrhelmut commented
Merging, thanks for the effort!

2024-02-10 09:21 UTC, merged

2024-02-10 09:23 UTC, SimonDarksideJ commented
Fantastic work @JakeLegendXIII and thanks for the tests, which ensure functionally continues to work as changes are made.