[Documentation] Update XML documentation
MonoGame/MonoGame pull request #8586
Opened 2024-11-21 20:40 UTC by theLaffa

Partially addresses #8165

### XML Documentation 

This PR aims to add new and update existing XML documentation to various public members with the intent to reduce build warnings

2025-01-06 18:16 UTC, AristurtleDev requested changes
Other than the remarks left, I would suggest checking for consistency with documentation on constructors.  Some are worded as "Initializes a new" and some are worded as "Creates a new".

2025-01-06 18:16 UTC, AristurtleDev commented on MonoGame.Framework.Content.Pipeline/Processors/TextureProcessor.cs
> +        /// Must be set to <c>true</c> to use the color key.
Use `<see langword="true"/>` instead of `<c>` blocks

2025-01-06 18:16 UTC, AristurtleDev commented on MonoGame.Framework.Content.Pipeline/Processors/TextureProcessor.cs
> +                    throw;
This should be in a separate PR since this PR is focused on documentation only.

2025-01-06 18:16 UTC, AristurtleDev commented on MonoGame.Framework.Content.Pipeline/Processors/TextureProcessor.cs
> +            texProfile.ConvertTexture(context, input, TextureFormat, false);
Don't add/remove white space for the sake of doing it, it clutters the PR and makes it harder to read through changes.  This was probably done by an auto format on document saving.

## Reference:
- [DO NOT send PRs for code style changes or make code changes just for the sake of style.](https://github.com/MonoGame/MonoGame/blob/develop/CONTRIBUTING.md#quick-guidelines)

2025-01-06 18:16 UTC, AristurtleDev commented on MonoGame.Framework.Content.Pipeline/Serialization/Compiler/ContentTypeWriter.cs
> +
Don't add/remove white space for the sake of doing it, it clutters the PR and makes it harder to read through changes.  This was probably done by an auto format on document saving.

## Reference:
- [DO NOT send PRs for code style changes or make code changes just for the sake of style.](https://github.com/MonoGame/MonoGame/blob/develop/CONTRIBUTING.md#quick-guidelines)

2025-01-06 18:16 UTC, AristurtleDev commented on MonoGame.Framework.Content.Pipeline/Serialization/Intermediate/ContentTypeSerializer.cs
> +        {
Don't add/remove white space for the sake of doing it, it clutters the PR and makes it harder to read through changes.  This was probably done by an auto format on document saving.

## Reference:
- [DO NOT send PRs for code style changes or make code changes just for the sake of style.](https://github.com/MonoGame/MonoGame/blob/develop/CONTRIBUTING.md#quick-guidelines)

2025-01-06 18:16 UTC, AristurtleDev commented on MonoGame.Framework.Content.Pipeline/Serialization/Intermediate/ContentTypeSerializer.cs
> +}
Don't add/remove white space for the sake of doing it, it clutters the PR and makes it harder to read through changes.  This was probably done by an auto format on document saving.

## Reference:
- [DO NOT send PRs for code style changes or make code changes just for the sake of style.](https://github.com/MonoGame/MonoGame/blob/develop/CONTRIBUTING.md#quick-guidelines)

2025-01-06 18:16 UTC, AristurtleDev commented on MonoGame.Framework.Content.Pipeline/Serialization/Intermediate/ContentTypeSerializerT.cs
> -
Don't add/remove white space for the sake of doing it, it clutters the PR and makes it harder to read through changes.  This was probably done by an auto format on document saving.

## Reference:
- [DO NOT send PRs for code style changes or make code changes just for the sake of style.](https://github.com/MonoGame/MonoGame/blob/develop/CONTRIBUTING.md#quick-guidelines)

2025-01-06 18:16 UTC, AristurtleDev commented on MonoGame.Framework.Content.Pipeline/Serialization/Intermediate/ContentTypeSerializerT.cs
> +}
Don't add/remove white space for the sake of doing it, it clutters the PR and makes it harder to read through changes.  This was probably done by an auto format on document saving.

## Reference:
- [DO NOT send PRs for code style changes or make code changes just for the sake of style.](https://github.com/MonoGame/MonoGame/blob/develop/CONTRIBUTING.md#quick-guidelines)

2025-01-06 18:16 UTC, AristurtleDev commented on MonoGame.Framework.Content.Pipeline/Serialization/Intermediate/IntermediateReader.cs
> +            return  nodeType == XmlNodeType.Element &&
Don't add/remove white space for the sake of doing it, it clutters the PR and makes it harder to read through changes.  This was probably done by an auto format on document saving.

## Reference:
- [DO NOT send PRs for code style changes or make code changes just for the sake of style.](https://github.com/MonoGame/MonoGame/blob/develop/CONTRIBUTING.md#quick-guidelines)

2025-01-06 18:16 UTC, AristurtleDev commented on MonoGame.Framework.Content.Pipeline/Serialization/Intermediate/IntermediateReader.cs
> +
Don't add/remove white space for the sake of doing it, it clutters the PR and makes it harder to read through changes.  This was probably done by an auto format on document saving.

## Reference:
- [DO NOT send PRs for code style changes or make code changes just for the sake of style.](https://github.com/MonoGame/MonoGame/blob/develop/CONTRIBUTING.md#quick-guidelines)

2025-01-06 18:16 UTC, AristurtleDev commented on MonoGame.Framework.Content.Pipeline/Serialization/Intermediate/IntermediateReader.cs
> +            return ReadObject(format, Serializer.GetTypeSerializer(typeof(T)), existingInstance);
Don't add/remove white space for the sake of doing it, it clutters the PR and makes it harder to read through changes.  This was probably done by an auto format on document saving.

## Reference:
- [DO NOT send PRs for code style changes or make code changes just for the sake of style.](https://github.com/MonoGame/MonoGame/blob/develop/CONTRIBUTING.md#quick-guidelines)

2025-01-06 18:16 UTC, AristurtleDev commented on MonoGame.Framework.Content.Pipeline/Serialization/Intermediate/IntermediateReader.cs
> +            return ReadRawObject(format, Serializer.GetTypeSerializer(typeof(T)), existingInstance);
Don't add/remove white space for the sake of doing it, it clutters the PR and makes it harder to read through changes.  This was probably done by an auto format on document saving.

## Reference:
- [DO NOT send PRs for code style changes or make code changes just for the sake of style.](https://github.com/MonoGame/MonoGame/blob/develop/CONTRIBUTING.md#quick-guidelines)

2025-01-06 18:16 UTC, AristurtleDev commented on MonoGame.Framework.Content.Pipeline/Serialization/Intermediate/IntermediateReader.cs
> +
Don't add/remove white space for the sake of doing it, it clutters the PR and makes it harder to read through changes.  This was probably done by an auto format on document saving.

## Reference:
- [DO NOT send PRs for code style changes or make code changes just for the sake of style.](https://github.com/MonoGame/MonoGame/blob/develop/CONTRIBUTING.md#quick-guidelines)

2025-01-06 18:16 UTC, AristurtleDev commented on MonoGame.Framework.Content.Pipeline/Serialization/Intermediate/IntermediateReader.cs
> +        /// Reads the next type in the
Don't add/remove white space for the sake of doing it, it clutters the PR and makes it harder to read through changes.  This was probably done by an auto format on document saving.

## Reference:
- [DO NOT send PRs for code style changes or make code changes just for the sake of style.](https://github.com/MonoGame/MonoGame/blob/develop/CONTRIBUTING.md#quick-guidelines)

2025-01-06 18:16 UTC, AristurtleDev commented on MonoGame.Framework.Content.Pipeline/Serialization/Intermediate/IntermediateReader.cs
> +}
Don't add/remove white space for the sake of doing it, it clutters the PR and makes it harder to read through changes.  This was probably done by an auto format on document saving.

## Reference:
- [DO NOT send PRs for code style changes or make code changes just for the sake of style.](https://github.com/MonoGame/MonoGame/blob/develop/CONTRIBUTING.md#quick-guidelines)

2025-01-06 18:16 UTC, AristurtleDev commented on MonoGame.Framework.Content.Pipeline/Serialization/Intermediate/IntermediateReader.cs
> +        /// Reads the next type in the
Additionally, i know you didn't write the original comment here, but this is an incomplete sentence if you want to add to it to finish it.

2025-01-06 18:16 UTC, AristurtleDev commented on MonoGame.Framework.Content.Pipeline/Serialization/Intermediate/IntermediateSerializer.cs
> +                // We still don't have a serializer then we
Don't add/remove white space for the sake of doing it, it clutters the PR and makes it harder to read through changes.  This was probably done by an auto format on document saving.

## Reference:
- [DO NOT send PRs for code style changes or make code changes just for the sake of style.](https://github.com/MonoGame/MonoGame/blob/develop/CONTRIBUTING.md#quick-guidelines)

2025-01-06 18:16 UTC, AristurtleDev commented on MonoGame.Framework.Content.Pipeline/Serialization/Intermediate/IntermediateSerializer.cs
> +            // We cache the serializer before we initialize it to
Don't add/remove white space for the sake of doing it, it clutters the PR and makes it harder to read through changes.  This was probably done by an auto format on document saving.

## Reference:
- [DO NOT send PRs for code style changes or make code changes just for the sake of style.](https://github.com/MonoGame/MonoGame/blob/develop/CONTRIBUTING.md#quick-guidelines)

2025-01-06 18:16 UTC, AristurtleDev commented on MonoGame.Framework.Content.Pipeline/Serialization/Intermediate/IntermediateSerializer.cs
> +}
Don't add/remove white space for the sake of doing it, it clutters the PR and makes it harder to read through changes.  This was probably done by an auto format on document saving.

## Reference:
- [DO NOT send PRs for code style changes or make code changes just for the sake of style.](https://github.com/MonoGame/MonoGame/blob/develop/CONTRIBUTING.md#quick-guidelines)

2025-01-06 18:16 UTC, AristurtleDev commented on MonoGame.Framework.Content.Pipeline/Serialization/Intermediate/IntermediateWriter.cs
> +
Don't add/remove white space for the sake of doing it, it clutters the PR and makes it harder to read through changes.  This was probably done by an auto format on document saving.

## Reference:
- [DO NOT send PRs for code style changes or make code changes just for the sake of style.](https://github.com/MonoGame/MonoGame/blob/develop/CONTRIBUTING.md#quick-guidelines)

2025-01-06 18:16 UTC, AristurtleDev commented on MonoGame.Framework.Content.Pipeline/Serialization/Intermediate/IntermediateWriter.cs
> +}
Don't add/remove white space for the sake of doing it, it clutters the PR and makes it harder to read through changes.  This was probably done by an auto format on document saving.

## Reference:
- [DO NOT send PRs for code style changes or make code changes just for the sake of style.](https://github.com/MonoGame/MonoGame/blob/develop/CONTRIBUTING.md#quick-guidelines)

2025-01-06 18:16 UTC, AristurtleDev commented on MonoGame.Framework/Platform/Graphics/GraphicsDebug.DirectX.cs
> +
Don't add/remove white space for the sake of doing it, it clutters the PR and makes it harder to read through changes.  This was probably done by an auto format on document saving.

## Reference:
- [DO NOT send PRs for code style changes or make code changes just for the sake of style.](https://github.com/MonoGame/MonoGame/blob/develop/CONTRIBUTING.md#quick-guidelines)

2025-01-06 18:16 UTC, AristurtleDev commented on MonoGame.Framework/Platform/Graphics/GraphicsDebug.DirectX.cs
> +
Don't add/remove white space for the sake of doing it, it clutters the PR and makes it harder to read through changes.  This was probably done by an auto format on document saving.

## Reference:
- [DO NOT send PRs for code style changes or make code changes just for the sake of style.](https://github.com/MonoGame/MonoGame/blob/develop/CONTRIBUTING.md#quick-guidelines)

2025-01-06 18:16 UTC, AristurtleDev commented on MonoGame.Framework/Platform/Graphics/States/BlendState.DirectX.cs
> +                // This is a new DX11 feature we should consider
Don't add/remove white space for the sake of doing it, it clutters the PR and makes it harder to read through changes.  This was probably done by an auto format on document saving.

## Reference:
- [DO NOT send PRs for code style changes or make code changes just for the sake of style.](https://github.com/MonoGame/MonoGame/blob/develop/CONTRIBUTING.md#quick-guidelines)

2025-01-06 18:16 UTC, AristurtleDev commented on MonoGame.Framework/Platform/Graphics/States/RasterizerState.DirectX.cs
> +                // To support feature level 9.1 these must
Don't add/remove white space for the sake of doing it, it clutters the PR and makes it harder to read through changes.  This was probably done by an auto format on document saving.

## Reference:
- [DO NOT send PRs for code style changes or make code changes just for the sake of style.](https://github.com/MonoGame/MonoGame/blob/develop/CONTRIBUTING.md#quick-guidelines)

2025-01-06 18:16 UTC, AristurtleDev commented on MonoGame.Framework/Platform/Graphics/Vertices/VertexBuffer.DirectX.cs
> +        /// <summary/>
Don't add/remove white space for the sake of doing it, it clutters the PR and makes it harder to read through changes.  This was probably done by an auto format on document saving.

## Reference:
- [DO NOT send PRs for code style changes or make code changes just for the sake of style.](https://github.com/MonoGame/MonoGame/blob/develop/CONTRIBUTING.md#quick-guidelines)

2025-02-09 13:11 UTC, SimonDarksideJ commented
Any chance @theLaffa we can get this PR updated with the above conflicts resolve please?

2025-02-15 14:26 UTC, SimonDarksideJ commented
Seems the updates are now causing build conflicts, if you can check you are in sync with develop, and also mark those conversations you have addressed as "Resolved" please @theLaffa

2025-02-15 20:56 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Audio/AudioContent.cs
> +        /// <param name="loopLength">The length of the loop.</param>
Added as a remark to be more descriptive

2025-02-15 20:56 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Audio/AudioContent.cs
> +        /// <param name="loopStart">The start position of the loop.</param>
Added as a remark to be more descriptive

2025-02-15 20:59 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Audio/AudioContent.cs
> +    /// Encapsulates and provides operations, such as format conversions, on the
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 20:59 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Audio/AudioContent.cs
> +        public ReadOnlyCollection<byte> Data
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 20:59 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Audio/AudioContent.cs
> +                if (_disposed || _data == null)
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 20:59 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Audio/AudioContent.cs
> +            }
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:00 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Audio/AudioProfile.cs
> -
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:00 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Builder/Convertors/StringToColorConverter.cs
> +                {
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:03 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Builder/PipelineBuildEvent.cs
> +        /// Gets or sets the parameters as an opaque dictionary.
Updated as suggested

2025-02-15 21:03 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Builder/PipelineBuildLogger.cs
> +}
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:04 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Builder/PipelineManager.cs
> +        /// Gets or sets the project directory.
Updated as suggested

2025-02-15 21:04 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Builder/PipelineManager.cs
> +        /// Gets or sets the output directory.
Updated as suggested

2025-02-15 21:05 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Builder/PipelineManager.cs
> +        /// <param name="intermediateDir">Intermediate directory.</param>
Used wording from the previous property descriptions

2025-02-15 21:05 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Builder/PipelineManager.cs
> +        /// Gets or sets the intermediate directory.
Updated as suggested

2025-02-15 21:05 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Builder/PipelineManager.cs
> +        /// <returns>Importer type name or <c>null</c> if not found.</returns>
Updated as suggested

2025-02-15 21:06 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Builder/PipelineManager.cs
> +        /// <returns>Name of the processor or <c>null</c> if not found.</returns>
Updated as suggested

2025-02-15 21:06 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Builder/PipelineManager.cs
> +        /// <returns>Type of the processor or <c>null</c> if not found.</returns>
Updated as suggested

2025-02-15 21:07 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Builder/PipelineManager.cs
> +        /// <param name="processorParameters">Opaque data dictionary containing the processor parameters.</param>
Updated as suggested

2025-02-15 21:08 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Builder/PipelineManager.cs
> +        /// <param name="processorParameters">Processor parameters.</param>
Reworked to include additional text from previous param description

2025-02-15 21:08 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Builder/PipelineManager.cs
> +        /// <param name="processorParameters">Processor parameters.</param>
Reworked to include additional text froom previous param description

2025-02-15 21:08 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Builder/PipelineProcessorContext.cs
> +            {
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:08 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Builder/PipelineProcessorContext.cs
> +                                                                                string importerName,
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:09 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Graphics/AlphaTestMaterialContent.cs
> -
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:09 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Graphics/AlphaTestMaterialContent.cs
> +        /// Gets or sets the alpha function property.
Updated as suggested

2025-02-15 21:10 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Graphics/Dxt1BitmapContent.cs
> +        /// <param name="height">The height in pixels of the bitmap.</param>
Updated grammar for clarity

2025-02-15 21:10 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Graphics/Dxt3BitmapContent.cs
> +        /// <param name="height">The height in pixels of the bitmap.</param>
Updated grammar for clarity

2025-02-15 21:10 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Graphics/FontDescription.cs
> +	        get { return characters; }
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:11 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Graphics/FontDescription.cs
> +			UseKerning = useKerning;
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:11 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Graphics/MeshHelper.cs
> +        /// We use a "Mean Weighted Equally" method generate vertex normals from triangle
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:11 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Graphics/MeshHelper.cs
> +                    // triangle area doesn't always have a direct relationship to the
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:11 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Graphics/MeshHelper.cs
> +            // All the indices are 1:1 with the others, so we
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:11 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Graphics/MeshHelper.cs
> +            // Lengyel, Eric. “Computing Tangent Space Basis Vectors for an Arbitrary Mesh”.
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:11 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Graphics/MeshHelper.cs
> +            // Hegde, Siddharth. "Messing with Tangent Space". Gamasutra, 2007.
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:11 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Graphics/MeshHelper.cs
> +                    // errors in other parts of the pipeline, we just take
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:11 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Graphics/MeshHelper.cs
> +                // TODO: This can be zero can cause NaNs on
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:12 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Graphics/MeshHelper.cs
> +        /// <param name="tolerance">Tolerance value that determines how close
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:12 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Graphics/MeshHelper.cs
> +        /// of this mesh. If you want to merge positions too, call
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:12 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Graphics/NodeContentCollection.cs
> +    /// Links from a child object to its parent are maintained as the collection contents are modified.
Links moved into remarks for clarity

2025-02-15 21:13 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Graphics/TextureProfile.cs
> +                throw;
Restored original throw with ex

2025-02-15 21:13 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/LoadedTypeCollection.cs
> +            AppDomain.CurrentDomain.AssemblyLoad += (sender, args) => ScanAssembly(args.LoadedAssembly);
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:13 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/OpenAssetImporter.cs
> +        ".smd", ".vta", // Valve Model
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:13 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/OpenAssetImporter.cs
> +        // http://assimp.sourceforge.net/lib_html/data.html and
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:14 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/OpenAssetImporter.cs
> +        /// where <i>TransformName</i> is one of:
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:14 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/OpenAssetImporter.cs
> +        {
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:14 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/OpenAssetImporter.cs
> +        /// the resulting content is the same as what the XNA FbxImporter
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:14 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/OpenAssetImporter.cs
> +                    ImportMaterials();
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:14 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/OpenAssetImporter.cs
> +                // TODO: What about AlphaTestMaterialContent, DualTextureMaterialContent,
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:14 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/OpenAssetImporter.cs
> +
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:14 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/OpenAssetImporter.cs
> +        }
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:14 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/OpenAssetImporter.cs
> +                        _identity,
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:17 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/OpenAssetImporter.cs
> +        /// <returns>Xna matrix.</returns>
Method apears to have been removed with merge from dev

2025-02-15 21:17 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/OpenAssetImporter.cs
> +        /// <param name="vector">Vector2D to convert.</param>
Method appears to have been removed with merge from dev

2025-02-15 21:17 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/OpenAssetImporter.cs
> +        /// Converts a Vector2D to a Xna Vector2.
Method appears to have been removed with merge from dev

2025-02-15 21:17 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/OpenAssetImporter.cs
> +        /// Converts a Vector3D to a Xna Vector3.
Method appears to have been removed with merge from dev

2025-02-15 21:18 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/OpenAssetImporter.cs
> +        /// Converts a Quaternion to a Xna Quaternion.
Method appears to have been removed with merge from dev

2025-02-15 21:18 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/OpenAssetImporter.cs
> +        /// Converts a Color4D to a Xna color without alpha.
Method appears to have been removed with merge from dev

2025-02-15 21:18 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/OpenAssetImporter.cs
> +        /// Converts a Vector3D to a Xna vector2 representing a texture coordinate.
Method appears to have been removed with merge from dev

2025-02-15 21:18 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/OpenAssetImporter.cs
> +        /// Converts a Color4D to a Xna color with alpha.
Method appears to have been removed with merge from dev

2025-02-15 21:19 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Processors/FontTextureProcessor.cs
> +                            // we have found the top, left of a image.
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:19 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Processors/FontTextureProcessor.cs
> +            // we need to call GtCharacterForIndex for each glyph in the Texture to
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:19 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Processors/LocalizedFontProcessor.cs
> +//-----------------------------------------------------------------------------
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:20 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Processors/TextureProcessor.cs
> +                    throw;
Restored the original code to throw ex;

2025-02-15 21:20 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Processors/TextureProcessor.cs
> +            texProfile.ConvertTexture(context, input, TextureFormat, false);
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:20 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Serialization/Intermediate/ContentTypeSerializer.cs
> +        {
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:20 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Serialization/Intermediate/ContentTypeSerializer.cs
> +}
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:20 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Serialization/Intermediate/ContentTypeSerializerT.cs
> -
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:20 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Serialization/Intermediate/ContentTypeSerializerT.cs
> +}
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:20 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Serialization/Intermediate/IntermediateReader.cs
> +            return  nodeType == XmlNodeType.Element &&
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:21 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Serialization/Intermediate/IntermediateReader.cs
> +
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:21 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Serialization/Intermediate/IntermediateReader.cs
> +            return ReadObject(format, Serializer.GetTypeSerializer(typeof(T)), existingInstance);
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:21 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Serialization/Intermediate/IntermediateReader.cs
> +            return ReadRawObject(format, Serializer.GetTypeSerializer(typeof(T)), default(T));
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:21 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Serialization/Intermediate/IntermediateReader.cs
> +            return ReadRawObject(format, typeSerializer, default(T));
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:21 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Serialization/Intermediate/IntermediateReader.cs
> +            return ReadRawObject(format, Serializer.GetTypeSerializer(typeof(T)), existingInstance);
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:21 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Serialization/Intermediate/IntermediateReader.cs
> +
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:21 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Serialization/Intermediate/IntermediateReader.cs
> +        /// Reads the next type in the
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:21 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Serialization/Intermediate/IntermediateReader.cs
> +}
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:22 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Serialization/Intermediate/IntermediateReader.cs
> +        /// Reads the next type in the
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:22 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Serialization/Intermediate/IntermediateSerializer.cs
> +                // We still don't have a serializer then we
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:22 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Serialization/Intermediate/IntermediateSerializer.cs
> +            // We cache the serializer before we initialize it to
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:22 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Serialization/Intermediate/IntermediateSerializer.cs
> +}
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:22 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Serialization/Intermediate/IntermediateWriter.cs
> +
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:22 UTC, theLaffa commented on MonoGame.Framework.Content.Pipeline/Serialization/Intermediate/IntermediateWriter.cs
> +}
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:22 UTC, theLaffa commented on MonoGame.Framework/Platform/Graphics/GraphicsDebug.DirectX.cs
> +
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:22 UTC, theLaffa commented on MonoGame.Framework/Platform/Graphics/GraphicsDebug.DirectX.cs
> +
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:22 UTC, theLaffa commented on MonoGame.Framework/Platform/Graphics/States/BlendState.DirectX.cs
> +                // This is a new DX11 feature we should consider
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:23 UTC, theLaffa commented on MonoGame.Framework/Platform/Graphics/States/DepthStencilState.DirectX.cs
> +                {   //use same settings as frontFace
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:23 UTC, theLaffa commented on MonoGame.Framework/Platform/Graphics/States/RasterizerState.DirectX.cs
> +                // To support feature level 9.1 these must
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:23 UTC, theLaffa commented on MonoGame.Framework/Platform/Graphics/Vertices/VertexBuffer.DirectX.cs
> +            // TODO: To use Immutable resources we would need to delay creation of
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:23 UTC, theLaffa commented on MonoGame.Framework/Platform/Graphics/Vertices/VertexBuffer.DirectX.cs
> +        /// <summary/>
Where possible, white space is returned to original. Editor settings corrected to match guideline

2025-02-15 21:29 UTC, theLaffa commented
Sorry for the delay, been doing parts of it between other jobs.

Builds passing now and conversations updated.

@AristurtleDev I'll review the constructor consistency in a separate PR... This one has become difficult to keep sync'd with dev

2025-02-16 00:17 UTC, AristurtleDev commented
All good, thanks for the work you did @theLaffa

2025-03-24 10:20 UTC, SimonDarksideJ approved these changes

2025-03-24 10:40 UTC, merged